### ISSUE TITLE
npm install @keydonix/uniswap-oracle-sdk-adapter is not on npm

### ISSUE THREAD

**Issue by BoxOfCereal** [Keydonix/uniswap-oracle#11]
Hello I've tried to install `npm install @keydonix/uniswap-oracle-sdk-adapter` and it appears to not be on NPM. Thank you for your time.

**Comment by MicahZoltu** [comment]
Sorry about that, looks like I forgot to actually publish it!  It is now available at [`@keydonix/uniswap-oracle-sdk-adapter`](https://www.npmjs.com/package/@keydonix/uniswap-oracle-sdk-adapter)

**Comment by MicahZoltu** [comment]
There is a bug that will cause it to not work with NodeJS 14.  I'm fixing that now and will push an update to both SDK and SDK Adapter shortly.

**Comment by MicahZoltu** [comment]
I have published fixes for NodeJS 14 (version 1.0.1) in case you were running into that.  Closing this issue for now, feel free to re-open if you still can't find it on NPM!

**Comment by BoxOfCereal** [comment]
Awesome! Thanks so much for replying and fixing this! I hated that I had to open _another_ issue, especially since the first was my fault. But I figured this one might come up anyway. Cheers!
