### ISSUE TITLE
0x prefix missing on util function

### ISSUE THREAD

**Issue by cloudonshore** [Keydonix/uniswap-oracle#13]
Hello! 
  I've been trying to use your library, and I'm getting a JSON RPC error with the `getStorageAtFactory`. When I inspect the RPC packet that is causing the error it looks like 

```
{
  "method": "eth_getStorageAt",
  "params": [
    "1b50b21225c2c7b3449ff776c368d14d51d05c5a",
    "0x6",
    "latest"
  ]
}
```

The address in the first param is missing a `0x` at the front of it (it should be `0x1b50b21225c2c7b3449ff776c368d14d51d05c5a`). When I re-add that missing `0x`, the RPC call returns successfully. 

Looking at the code, it looks like it might be the result of this util function. It looks like the `0x` prefix was never added to the string.
https://github.com/Keydonix/uniswap-oracle/blob/master/sdk-adapter/source/index.ts#L213

**Comment by epheph** [comment]
Thank you for the report, can you try version 1.0.2?

**Comment by cloudonshore** [comment]
Yes it is fixed, thanks
