### ISSUE TITLE
calling getPrice from solidity

### ISSUE THREAD

**Issue by ghost** [Keydonix/uniswap-oracle#21]
Hello, please how do I use getPrice from solidity, a simple demo will do, Thanks

**Comment by MicahZoltu** [comment]
You can check out the demo app here https://github.com/Keydonix/uniswap-oracle/blob/master/demo/contracts/PriceEmitter.sol

I also encourage you to join our Discord server at https://discord.gg/cM9A5v8 for more in depth assistance with using the oracle in your contracts.
