### ISSUE TITLE
Hi Keydonix

### ISSUE THREAD

**Issue by brainspacer** [Keydonix/uniswap-oracle#30]
Is there a version of Keydonix (or something similar?) for UniswapV3 and/or other high-liquidity AMM platforms?

**Comment by MicahZoltu** [comment]
Uniswap v3 has a built-in TWAP oracle you can use, so you don't need to use something like this.  We haven't built an oracle for anything other than Uniswap v2.

**Comment by MicahZoltu** [comment]
Closing for now as a question with an answer.  Feel free to comment or re-open if you have a follow-up!
